# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-11 02:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdirs', models.CharField(default='', max_length=204800)),
                ('files', models.CharField(default='', max_length=204800)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('object_pk', models.IntegerField(null=True)),
                ('is_regular', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.File')),
            ],
        ),
        migrations.CreateModel(
            name='RegularFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('received', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('digest', models.CharField(max_length=40)),
                ('path', models.CharField(max_length=4096)),
                ('finished', models.BooleanField(default=False)),
                ('links', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, null=True)),
                ('expire', models.DateTimeField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.File')),
            ],
        ),
    ]
