# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-11 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='expire',
            field=models.DateTimeField(null=True),
        ),
    ]
